import Head from 'next/head'
import Image from 'next/image' 
import { GetStaticProps } from 'next'

type IData = {
  title?: string;
  explanation?: string;
  url?: string;
  hdurl?: string;
  date?: string;
}

export default function Home({ datas }:any) {
  return (
    <>
      <Head>
        <title>Image By NASA</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <h1>{ datas.title }</h1>
        <a href={ datas.hdurl } target="_blank" rel="noopener noreferrer">
          <Image src={ datas.url } alt={ datas.url } width="1000" height="600" className="image"/>
        </a>
        <p>{ datas.explanation }</p>
        <span>{ datas.date[8] + datas.date[9] + ' / ' + datas.date[5] + datas.date[6] + ' / ' + datas.date[0] + datas.date[1] + datas.date[2] + datas.date[3] }</span>
      </main>
    </>
  )
}

export const getStaticProps:GetStaticProps = async (ctx) => {
  const res = await fetch(`https://api.nasa.gov/planetary/apod?api_key=${process.env.NEXT_PUBLIC_ENV_LOCAL_VARIABLE}`)
  const datas = await res.json()

  return {
    props: {
      datas
    },
    revalidate: 60 * 60 * 8     // 8 HOURS
  }
}