import Head from 'next/head'
import { useEffect, useState } from 'react'

type IData = {
  title?: string;
  explanation?: string;
  url?: string;
  hdurl?: string;
  date?: string;
}

export default function Home() {
  const [datas, setDatas] = useState<IData>({}) 

  useEffect(() => {
    const headers = { 'Content-Type': 'application/json' }
    fetch(`https://api.nasa.gov/planetary/apod?api_key=${process.env.NEXT_PUBLIC_ENV_LOCAL_VARIABLE}`, { headers })
        .then(response => response.json())
        .then(data => setDatas( data ));
  }, [])

  return (
    <>
      <Head>
        <title>Image By NASA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
        <link rel="icon" href="https://api.nasa.gov/assets/img/favicons/favicon-192.png" />
      </Head>

      <main>
        <h1>{ datas.title }</h1>
        <a href={ datas.hdurl } target="_blank" rel="noopener noreferrer">
          <img src={ datas.url } alt={ datas.url } />
        </a>
        <p>{ datas.explanation }</p>
        <span>{ datas.date }</span>
      </main>
      
    </>
  )
}
